const express = require('express')
const { signup, login, getUser, logout, resetPassword, updateProfile , sendOtp, createPost, getPost } = require('../controllers/user-controller')
const { verifyToken } = require('../middleware/authMiddleware')
const router = express.Router()
const {upload} = require('../middleware/multer')
router.post('/signup',signup)
router.post('/login',login)
router.post('/sendOtp', sendOtp)
router.get('/user',getUser)
router.post('/logout',verifyToken,logout)
router.patch('/resetPassword', resetPassword)
router.patch('/update',verifyToken,upload.single('image'),updateProfile)

router.post('/createPost',upload.single('image'),createPost) 
router.get('/getPosts',getPost)
module.exports = router  